#!/bin/bash

#Author: Era Scarecrow <rtcvb32@yahoo.com>
#License: GPL 2
#Date: 22 Sep 2021
#Description: Convert Slax bundles to LZO
#
#Convert Slax's default XZ to LZO. This is a standalone script for any bundles, not the core.
#Recommended you do this in /tmp.

#root required in MOST cases, as we will likely make root or other users
#In workaround root rquired to mount
if [ ! "`whoami`" = 'root' ]; then
	echo "Requires root..."
	su
	if [ ! "`whoami`" = 'root' ]; then
		echo "Not root, probably wouldn't work"
		exit 1
	fi
fi

#Create mount point
mkdir /tmp/repack.sb

for X;
do
	
	mount "$X" /tmp/repack.sb -t squashfs -o loopback

	printf "Repacking: %s" "$X"
	mksquashfs /tmp/repack.sb "$X.sqfs" -comp lzo -b 1024K -always-use-fragments >/dev/null
	printf "\t%s  ->  %s\n"  `du -h "$X" | sed -E -e 's/[^a-zA-Z0-9].*//'`  `du -h "$X.sqfs" | sed -E -e 's/[^a-zA-Z0-9].*//'`

	umount /tmp/repack.sb
	mv "$X.sqfs" "$X"
	sync
done

#Cleanup mount point
rm -fr /tmp/repack.sb
